### ISSUE TITLE
Obscure Dockerfile feature needs comment

### ISSUE THREAD

**Issue by alejandro-colomar** [alejandro-colomar/www.alejandro-colomar.com#10]
https://github.com/alejandro-colomar/www.alejandro-colomar.com/blob/8c4e89f551411bf4cdec36abb9f0e3af207a830f/Dockerfile#L22

```
RUN									\
	for package in $(						\
		for x in 0 1 2 3 4 5 6 7 8 9;				\
		do							\
			apk list					\
			| awk /nginx/'{ print $1 }'			\
			| awk -F-$x  '{ print $1 }'			\
			| grep -v '\-[0-9]';				\
		done							\
		| sort							\
		| uniq							\
		| grep -v ^nginx$					\
	);								\
	do								\
		apk del $package;					\
	done
```

This code is not obvious, and a comment about what it does (and possibly why) would be appropriate.

This might help: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#8-commenting

@secobau

**Comment by secobau** [comment]
It is very obvious: it removes any nginx module but 'nginx' itself.
